In [1]:
import pandas as pd

df = pd.read_csv("Superstore.csv", encoding="latin1")
df.head()

,order_date,customer_name,country,category,sub_category,sales,quantity,discount,profit,shipping_cost,year,revenue
0,01-01-2011,Toby Braunhardt,Algeria,Office Supplies,Storage,408,2.0,0.0,106.140,35.46,2011.0,408.0
1,02-01-2011,Joseph Holt,Australia,Office Supplies,Supplies,120,3.0,0.1,36.036,9.72,2011.0,120.0
2,03-01-2011,Annie Thurman,Hungary,Office Supplies,Storage,66,4.0,0.0,29.640,8.17,2011.0,66.0
3,04-01-2011,Eugene Moren,Sweden,Office Supplies,Paper,45,3.0,0.5,-26.055,4.82,2011.0,45.0
4,05-01-2011,Joseph Holt,Australia,Furniture,Furnishings,114,5.0,0.1,37.770,4.70,2011.0,114.0

In [2]:
top_products = df.groupby("sub_category")["revenue"].sum().sort_values(ascending=False)
top_products.head()

sub_category
Phones       70142.0
Chairs       62407.0
Machines     52819.0
Storage      47636.0
Bookcases    45518.0
Name: revenue, dtype: float64

In [3]:
monthly_sales = df.groupby("year")["revenue"].sum()
monthly_sales

year
2011.0    477745.0
2012.0         0.0
2013.0         0.0
2014.0         0.0
Name: revenue, dtype: float64

In [4]:
df.groupby("sub_category")["revenue"].sum()

sub_category
Accessories    20541.0
Appliances     34994.0
Art            16463.0
Binders        13047.0
Bookcases      45518.0
Chairs         62407.0
Copiers        39085.0
Envelopes       6877.0
Fasteners       3676.0
Furnishings    16769.0
Labels          2760.0
Machines       52819.0
Paper           8388.0
Phones         70142.0
Storage        47636.0
Supplies       10278.0
Tables         26345.0
Name: revenue, dtype: float64

In [5]:
df.groupby("year")["revenue"].sum()

year
2011.0    477745.0
2012.0         0.0
2013.0         0.0
2014.0         0.0
Name: revenue, dtype: float64

In [6]:
df.describe()

,quantity,discount,profit,shipping_cost,year,revenue
count,44580.000000,44580.000000,44580.000000,44580.000000,44580.000000,2018.000000
mean,3.472880,0.141656,29.046674,26.298243,2012.928421,236.741824
std,2.276932,0.211337,173.995025,57.073323,0.977558,659.469828
min,1.000000,0.000000,-6599.978000,0.000000,2011.000000,1.000000
25%,2.000000,0.000000,0.000000,2.610000,2012.000000,29.000000
50%,3.000000,0.000000,9.300000,7.790000,2013.000000,81.000000
75%,5.000000,0.200000,36.960000,24.532500,2014.000000,238.000000
max,14.000000,0.850000,8399.976000,933.570000,2014.000000,22638.000000

In [7]:
df["order_date"] = pd.to_datetime(df["order_date"], dayfirst=True)

In [8]:
df = pd.read_csv("superstore.csv", encoding="latin1")
df.head()

,order_date,customer_name,country,category,sub_category,sales,quantity,discount,profit,shipping_cost,year,revenue
0,01-01-2011,Toby Braunhardt,Algeria,Office Supplies,Storage,408,2.0,0.0,106.140,35.46,2011.0,408.0
1,02-01-2011,Joseph Holt,Australia,Office Supplies,Supplies,120,3.0,0.1,36.036,9.72,2011.0,120.0
2,03-01-2011,Annie Thurman,Hungary,Office Supplies,Storage,66,4.0,0.0,29.640,8.17,2011.0,66.0
3,04-01-2011,Eugene Moren,Sweden,Office Supplies,Paper,45,3.0,0.5,-26.055,4.82,2011.0,45.0
4,05-01-2011,Joseph Holt,Australia,Furniture,Furnishings,114,5.0,0.1,37.770,4.70,2011.0,114.0

In [9]:
df.groupby(["category", "year"])["sales"].sum()

category         year
Furniture        2011.0    114667211854159691,64838493242,574155262,47998...
                 2012.0    6274521781,35211650813954251923835136434491016...
                 2013.0    1,3582,1901,36224623161,6371,5672351742171,593...
                 2014.0    107474311141254991348640140230913167881,003328...
Office Supplies  2011.0    4081206645552763381231353652628147617186140149...
                 2012.0    2,8221,230417867247201061272614272417358942071...
                 2013.0    29915524241785951059946641610162291,5331371121...
                 2014.0    1571602031529954354138138404319513048231443961...
Technology       2011.0    3149121931956922316638283924452743881747562,17...
                 2012.0    4131,18891627424526510329463903981555804247108...
                 2013.0    1,6497291152,0221,0543699771492322937676320311...
                 2014.0    67784633230230854738213955561732,0976962895242...
Name: sales, dtype: str

In [10]:
monthly = df.groupby("year")["sales"].sum()

best_year = monthly.idxmax()
worst_year = monthly.idxmin()

best_year, worst_year

(np.float64(2014.0), np.float64(2013.0))

In [11]:
yearly = df.groupby("year")["sales"].sum()

best_year = yearly.idxmax()
worst_year = yearly.idxmin()

best_year, worst_year

(np.float64(2014.0), np.float64(2013.0))

In [12]:
monthly = df.groupby("year")["sales"].sum()

best_month = monthly.idxmax()
worst_month = monthly.idxmin()

best_month, worst_month

(np.float64(2014.0), np.float64(2013.0))

In [13]:
df.groupby("category")["profit"].sum()

category
Furniture          252320.1652
Office Supplies    460774.2165
Technology         581806.3300
Name: profit, dtype: float64

In [14]:
table = df.groupby("category")["sales"].sum().reset_index()
table

          category                                              sales
0        Furniture  114667211854159691,64838493242,574155262,47998...
1  Office Supplies  4081206645552763381231353652628147617186140149...
2       Technology  3149121931956922316638283924452743881747562,17...

In [15]:
df.sort_values(by="sales", ascending=False).head()

,order_date,customer_name,country,category,sub_category,sales,quantity,discount,profit,shipping_cost,year,revenue
7602,28-11-2011,Brian Thompson,United States,Technology,Machines,999,5.0,0.4,-199.7700,112.39,2011.0,NaN
14710,24-08-2012,Cassandra Brandow,United States,Office Supplies,Storage,999,7.0,0.2,124.9290,69.76,2012.0,NaN
40454,28-06-2014,Bruce Stewart,Guatemala,Office Supplies,Appliances,999,3.0,0.0,179.8200,75.80,2014.0,NaN
8823,28-12-2011,Maribeth Dona,United States,Office Supplies,Storage,999,9.0,0.0,29.9646,76.28,2011.0,NaN
20773,06-02-2013,Toby Carlisle,India,Furniture,Tables,998,3.0,0.0,419.1300,61.25,2013.0,NaN

In [16]:
df.groupby("category")["sales"].agg(["sum", "max", "min"])

                                                               sum  max    min
category
Furniture        114667211854159691,64838493242,574155262,47998...  998  1,001
Office Supplies  4081206645552763381231353652628147617186140149...  999      0
Technology       3149121931956922316638283924452743881747562,17...  999      1

In [17]:
pivot = pd.pivot_table(df, values="sales", index="category", aggfunc="sum")
pivot

                                                             sales
category
Furniture        114667211854159691,64838493242,574155262,47998...
Office Supplies  4081206645552763381231353652628147617186140149...
Technology       3149121931956922316638283924452743881747562,17...

In [18]:
pivot2 = pd.pivot_table(df, values="sales", index="category", columns="year", aggfunc="sum")
pivot2

year,2011.0,2012.0,2013.0,2014.0
category,,,,
Furniture,"114667211854159691,64838493242,574155262,47998...","6274521781,35211650813954251923835136434491016...","1,3582,1901,36224623161,6371,5672351742171,593...","107474311141254991348640140230913167881,003328..."
Office Supplies,4081206645552763381231353652628147617186140149...,"2,8221,230417867247201061272614272417358942071...","29915524241785951059946641610162291,5331371121...",1571602031529954354138138404319513048231443961...
Technology,"3149121931956922316638283924452743881747562,17...","4131,18891627424526510329463903981555804247108...","1,6497291152,0221,0543699771492322937676320311...","67784633230230854738213955561732,0976962895242..."

In [19]:
df["sales"] = pd.to_numeric(df["sales"], errors="coerce")

In [20]:
df.groupby("category")["sales"].sum().sort_values(ascending=False)

category
Office Supplies    2427096.0
Technology         2306888.0
Furniture          2091012.0
Name: sales, dtype: float64

In [21]:
df["rank"] = df["sales"].rank(ascending=False)

In [22]:
df.groupby("category")[["sales", "profit"]].sum()

                     sales       profit
category
Furniture        2091012.0  252320.1652
Office Supplies  2427096.0  460774.2165
Technology       2306888.0  581806.3300

In [23]:
df["profit_status"] = df["profit"].apply(lambda x: "Loss" if x < 0 else "Profit")

In [24]:
df[(df["sales"] > 5000) & (df["profit"] > 0)]

Empty DataFrame
Columns: [order_date, customer_name, country, category, sub_category, sales, quantity, discount, profit, shipping_cost, year, revenue, rank, profit_status]
Index: []

In [25]:
df[df["sales"] > 5000]

Empty DataFrame
Columns: [order_date, customer_name, country, category, sub_category, sales, quantity, discount, profit, shipping_cost, year, revenue, rank, profit_status]
Index: []

In [26]:
df["category"].value_counts()

category
Office Supplies    27215
Technology          8828
Furniture           8537
Name: count, dtype: int64

In [27]:
pd.crosstab(df["category"], df["profit_status"])

profit_status    Loss  Profit
category
Furniture        2677    5860
Office Supplies  6062   21153
Technology       2093    6735

In [28]:
df["category"].value_counts(normalize=True) * 100

category
Office Supplies    61.047555
Technology         19.802602
Furniture          19.149843
Name: proportion, dtype: float64

In [29]:
df[["sales", "profit"]].corr()

           sales    profit
sales   1.000000  0.254547
profit  0.254547  1.000000

In [30]:
df["sales_group"] = pd.cut(df["sales"], bins=5)
df["sales_group"].value_counts()

sales_group
(-0.999, 199.8]    31302
(199.8, 399.6]      5973
(399.6, 599.4]      2587
(599.4, 799.2]      1540
(799.2, 999.0]       917
Name: count, dtype: int64

In [31]:
df["sales"].quantile([0.25, 0.5, 0.75])

0.25     29.0
0.50     77.0
0.75    209.0
Name: sales, dtype: float64

In [32]:
df["sales"].std()

np.float64(201.09817571387094)

In [33]:
df["sales_level"] = df["sales"].apply(lambda x: "High" if x > 5000 else "Low")

In [34]:
df["category_code"] = df["category"].map({
    "Technology": 1,
    "Furniture": 2,
    "Office Supplies": 3
})

In [35]:
Q1 = df["sales"].quantile(0.25)
Q3 = df["sales"].quantile(0.75)

outliers = df[(df["sales"] < Q1) | (df["sales"] > Q3)]

In [36]:
df["pct_change"] = df["sales"].pct_change()

In [37]:
df["rank_in_category"] = df.groupby("category")["sales"].rank(ascending=False)

In [38]:
df1 = df[["sub_category", "sales"]]
df2 = df[["sub_category", "profit"]]

merged = pd.merge(df1, df2, on="sub_category")
merged.head()

  sub_category  sales    profit
0      Storage  408.0  106.1400
1      Storage  408.0   29.6400
2      Storage  408.0 -122.8005
3      Storage  408.0  -45.9018
4      Storage  408.0    8.7000

In [39]:
df["category_code"] = df["category"].map({
    "Technology": 1,
    "Furniture": 2,
    "Office Supplies": 3
})

In [40]:
Q1 = df["sales"].quantile(0.25)
Q3 = df["sales"].quantile(0.75)

outliers = df[(df["sales"] < Q1) | (df["sales"] > Q3)]

In [41]:
df["pct_change"] = df["sales"].pct_change()

In [42]:
df["rank_in_category"] = df.groupby("category")["sales"].rank(ascending=False)

In [43]:
pd.merge(df1, df2, on="sub_category")

          sub_category  sales    profit
0              Storage  408.0  106.1400
1              Storage  408.0   29.6400
2              Storage  408.0 -122.8005
3              Storage  408.0  -45.9018
4              Storage  408.0    8.7000
...                ...    ...       ...
163596299        Paper   12.0   54.3000
163596300        Paper   12.0   23.2350
163596301        Paper   12.0   22.7700
163596302        Paper   12.0    9.3000
163596303        Paper   12.0    5.7624

[163596304 rows x 3 columns]

In [44]:
df.memory_usage()

Index                  132
order_date          396496
customer_name       396496
country             396496
category            396496
sub_category        396496
sales               396496
quantity            396496
discount            396496
profit              396496
shipping_cost       396496
year                396496
revenue             396496
rank                396496
profit_status       396496
sales_group          49642
sales_level         396496
category_code       396496
pct_change          396496
rank_in_category    396496
dtype: int64

In [45]:
df.memory_usage()

Index                  132
order_date          396496
customer_name       396496
country             396496
category            396496
sub_category        396496
sales               396496
quantity            396496
discount            396496
profit              396496
shipping_cost       396496
year                396496
revenue             396496
rank                396496
profit_status       396496
sales_group          49642
sales_level         396496
category_code       396496
pct_change          396496
rank_in_category    396496
dtype: int64

In [46]:
df.memory_usage()

Index                  132
order_date          396496
customer_name       396496
country             396496
category            396496
sub_category        396496
sales               396496
quantity            396496
discount            396496
profit              396496
shipping_cost       396496
year                396496
revenue             396496
rank                396496
profit_status       396496
sales_group          49642
sales_level         396496
category_code       396496
pct_change          396496
rank_in_category    396496
dtype: int64

In [47]:
df.memory_usage()

Index                  132
order_date          396496
customer_name       396496
country             396496
category            396496
sub_category        396496
sales               396496
quantity            396496
discount            396496
profit              396496
shipping_cost       396496
year                396496
revenue             396496
rank                396496
profit_status       396496
sales_group          49642
sales_level         396496
category_code       396496
pct_change          396496
rank_in_category    396496
dtype: int64

In [48]:
df = df.convert_dtypes()

C:\Users\Sachin\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\dtypes\cast.py:968: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():
C:\Users\Sachin\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\dtypes\cast.py:995: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():

In [49]:
df = df.convert_dtypes()

In [50]:
df.to_csv("final_output.csv", index=False)

In [51]:
df.groupby("category")["sales"].agg(["sum","mean","max"])

                     sum        mean  max
category
Furniture        2091012  271.102295  998
Office Supplies  2427096   90.732561  999
Technology       2306888   293.64664  999

In [52]:
pd.pivot_table(df, values="sales", index="category", columns="year", aggfunc="sum")

year               2011    2012    2013    2014
category
Furniture        186572  495925  677142  731373
Office Supplies  217206  608040  744415  857435
Technology       203334  577534  685464  840556

In [53]:
df.groupby("category")["sales"].sum()

category
Furniture          2091012
Office Supplies    2427096
Technology         2306888
Name: sales, dtype: Int64

In [57]:
df.groupby("category")["sales"].sum().idxmax()

'Office Supplies'

In [58]:
df.groupby("category")["sales"].sum().idxmin()

'Furniture'

In [64]:
df.groupby("category")["sales"].sum().sort_values(ascending=False)

category
Office Supplies    2427096
Technology         2306888
Furniture          2091012
Name: sales, dtype: Int64